[tools]
fd = "latest"
fzf = "latest"
node = "latest"
python = "latest"
rg = "latest"
chezmoi = "latest"
uv = "latest"
just = "latest"
zellij = "latest"
neovim = "latest"
gh = "latest"
rclone = "latest"
flyctl = "latest"
neonctl = "latest"
"aqua:satococoa/wtp" = "latest"
"aqua:minio/mc" = "latest"
"aqua:jqlang/jq" = "latest"
mutagen = "latest"
micromamba = "latest"
